# Slate bot which apply the "Slate" tag and close issue labeled "Fix to be tested"
#
# Full configuration documentation : https://github.com/actions/stale#all-options
# =======================
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 0
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Label to use when marking an issue as stale
staleLabel: "🤖 Slate"
# Issues with these labels will never be considered stale
#exemptLabels:
#  - pinned
#  - security
# Only issues/PRs with ANY of these labels are checked
any-labels: 
  - "👍 Fix to be tested"
# Order to get issues/PRs
ascending: true
# Remove stale label from issues on updates/comments
remove-issue-stale-when-updated: true
# Remove stale label from PRs on updates/comments
remove-pr-stale-when-updated: true
# Dry-run
operations-per-run: 0
debug-only: true