# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Continuous project validation

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ 2024-06 ]
    paths-ignore:
      - 'travis/**'

  workflow_dispatch: # For manual trigger

jobs:

  ci-handler:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          echo "${{ github.event.head_commit.message }}"

      - name: Validate Commit Message
        if: ${{ contains(github.event.head_commit.message, 'ci release') }}
        run: |
          echo "'ci release' Commit message detected!"
          echo "Triggering workflow '/.github/workflows/travis-gama-release.yaml'..."
          releaseVersion=$(date +"%Y").$(date +"%m").0
          #
          # Manually trigger the target workflow
          curl --request POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            --data "{\"event_type\": \"ci_release\", \"ref\": \"${{ github.sha }}\", \"inputs\": { \"IS_STABLE_RELEASE\": \"false\", \"tag\": \"$releaseVersion\" }}" \
            https://api.github.com/repos/gama-platform/gama/dispatches

  compiling-gama:
    needs: ci-handler
    if: ${{ !contains(github.event.head_commit.message, 'ci release') }}
    name: Compiling GAMA
    uses: ./.github/workflows/travis-build.yaml
    with:
      get_testing_compiled_archives: true
      get_all_archives_for_release: false

  testing-gama:
    name: Testing built GAMA
    needs: compiling-gama
    uses: ./.github/workflows/travis-build-test.yaml
